version: '3.3'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: gandalf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - gandalf_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db-test:
    image: postgres:16
    environment:
      POSTGRES_DB: gandalf-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - gandalf_test_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  gandalf_data:
  gandalf_test_data:
  redis_data:
