version: '3.3'

services:
  db:
    image: mariadb:10.8
    volumes:
      - db_data:/var/lib/mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: strong-password
      MYSQL_DATABASE: gandalf
      MYSQL_USER: gandalf
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  db-test:
    image: mariadb:10.8
    volumes:
      - db-test_data:/var/lib/mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: strong-password
      MYSQL_DATABASE: gandalf-test
      MYSQL_USER: gandalf
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  db_data:
  db-test_data:
  redis_data:
