version: '3.3'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: gandalf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - gandalf_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "3003:3000"
    volumes:
      - storage:/app/storage
    environment:
      DATABASE_URL: postgresql://postgres:password@db/gandalf
      RAILS_LOG_TO_STDOUT: 1
      SECRET_AUTH_USERNAME: admin
      SECRET_AUTH_PASSWORD: admin-password
      RAILS_SERVE_STATIC_FILES: 1

  sidekiq:
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - storage:/app/storage
    environment:
      DATABASE_URL: postgresql://postgres:password@db/gandalf
      REDIS_URL: redis://redis:6379
    entrypoint: bundle exec sidekiq

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  gandalf_data:
  redis_data:
  storage:
