default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 3306
  database: gandalf
  username: gandalf
  password: password
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default

test:
  <<: *default
  database: gandalf-test
  port: 3307

production:
  <<: *default
