default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: postgres
  password: password
  encoding: utf8
  port: 5432

development:
  <<: *default
  database: gandalf

test:
  <<: *default
  database: gandalf-test
  port: 5433

production:
  <<: *default
